//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentifyxCommunications.Domain.MessageResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RentifyxCommunications.Domain.MessageResource.ValidationMessageResource", typeof(ValidationMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correlation id is required..
        /// </summary>
        public static string CORRELATION_ID_REQUIRED {
            get {
                return ResourceManager.GetString("CORRELATION_ID_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recipient id is required..
        /// </summary>
        public static string RECIPIENT_ID_REQUIRED {
            get {
                return ResourceManager.GetString("RECIPIENT_ID_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recipient email is required..
        /// </summary>
        public static string RECIPIENT_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("RECIPIENT_EMAIL_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Template id is required..
        /// </summary>
        public static string TEMPLATE_ID_REQUIRED {
            get {
                return ResourceManager.GetString("TEMPLATE_ID_REQUIRED", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Channel &apos;{Channel}&apos; is not recognized..
        /// </summary>
        public static string CHANNEL_INVALID {
            get {
                return ResourceManager.GetString("CHANNEL_INVALID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payload is required..
        /// </summary>
        public static string PAYLOAD_REQUIRED {
            get {
                return ResourceManager.GetString("PAYLOAD_REQUIRED", resourceCulture);
            }
        }
    }
}
